server:
  address: localhost
  port: 8081
#  tomcat:
#    uri-encoding: utf-8

spring:
   application:
     name: angel

elasticsearch:
   host: localhost
   port: 9200

mconfig:
  swagger-ui-open: true  #是否开启swagger接口文档

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xhy.angel.domain
  type-handlers-package: com.xhy.angel.domain

#pagehelper:
#  helper-dialect: mysql
#  params: count=countSql
#  reasonable: true
#  support-methods-arguments: true

#spark:
#  app-name: angel-spark
#  master: local[4]
#  spark-home: 1

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Avalai@720494
    url: jdbc:mysql://localhost:3306/angel?serverTimezone=UTC
    username: root

  #devtools:
  #  restart:
  #    additional-paths: src/main/java
  #    enabled: true

  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      auto-commit-interval: 100
      auto-offset-reset: earliest
      enable-auto-commit: true
      group-id: test-hello-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      batch-size: 16384
      buffer-memory: 33554432
      retries: 0
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    producerd:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer

  #thymeleaf:
  #  cache: false
